### ISSUE TITLE
Melhorando página de Laboratório

### ISSUE THREAD

**Issue by diegorojas** [brainwp/imagicas-theme#2]
Seguinte, o que precisa ser somado na interface que temos é uma opção lá na aba "laboratorio" do admin:

![dev-imagicas-lab](https://cloud.githubusercontent.com/assets/3632627/4997562/37625974-69b7-11e4-8c93-c2a6d7d5c274.png)

Preciso que o usuário tenha uma opção (checkbox) assim: 
"Abrir video destacado ao acessar a página?"

Se não, ok. Morreu.

Se sim, em baixo disso apareceria ou se ativaria uma lista do cpt "laboratorio" na taxonomia "destacado". Ai a pessoa escolhe uma, só uma.

A idéia é um js que clique naquele destaque ao acessar a página. Ai sempre que essa opção estiver ticada, algum vídeo (ou reveal-modal) estará em destaque na página Laboratórios.

Ok?

**Comment by diegorojas** [comment]
@matheusgimenez conforme falamos, resolva ai só com um campo para o ID da pagina para destacar na Lab. 

Ai o texto pode ser:
"Coloque o ID da página que quer ver destacada ao abrir"

**Comment by matheusgimenez** [comment]
Eu fiz por link, achei melhor assim, id é meio tenso de um usuário comum conseguir.

Funcionando já nesse ultimo commit que dei (esqueci de colocar o issue no nome, por isso nao apareceu aqui, hehe)

**Comment by diegorojas** [comment]
Maheus, subi os arquivos seus no Beta e não consegui ver isso aqui funcionando. Só que tava na cliente e ai fiz um commit em cima já com mudanças que peguei com na hora, ok? 

Dá uma verificada e já sobe resolvido para o beta por favor? Qq coisa me avisa.

**Comment by matheusgimenez** [comment]
Vish.. estranho, no meu dev aqui ta funcionando, veja:
http://wp.codeispoetry.info/imagicas/laboratorio/

**Comment by diegorojas** [comment]
Tendi, mas ai não estão minhas ultimas alterações... será que eu passei por cima? Ou vc num tinha subido? poderia verificar?

**Comment by diegorojas** [comment]
@matheusgimenez  meu rei, me dê algum alô sobre isso? É hoje que isso vai pro ar...

**Comment by matheusgimenez** [comment]
Beleza.. vou ver isso agora

**Comment by matheusgimenez** [comment]
http://beta.brasa.art.br/imagicas/laboratorio/

Agora está ok!

**Comment by diegorojas** [comment]
Perfeito! Obrigado
