### ISSUE TITLE
Reveal modal depois de fechar mantém audio do player

### ISSUE THREAD

**Issue by diegorojas** [brainwp/imagicas-theme#3]
Ei @matheusgimenez blza? Seguinte, agora publicamos o site e tamo na cobrança, mas veja um bug na página laboratório, ou melhor no modal lá.
beta.brasa.art.br/imagicas/laboratorio/

Ali que todos os modais são de videos fica fácil. Ao dar play em um video e fechar o modal, o audio do vídeo continua. Pode ver ai de no javascript dar um kill no audio?

**Comment by matheusgimenez** [comment]
Vou fazer isso agora

**Comment by matheusgimenez** [comment]
Pega ai (branch beta):
https://github.com/brasadesign/reveal-modal/tree/beta

**Comment by diegorojas** [comment]
Perfeito! valeu!

**Comment by diegorojas** [comment]
ah...  somei na produção da brasa e no beta!
