### ISSUE TITLE
Clientes Responsivo

### ISSUE THREAD

**Issue by diegorojas** [brainwp/imagicas-theme#6]
Aqui nessa página depois de aplicado o menu, precisa ver porque a imagem está ficando distorcida nas versões menores. Ai precisa resolver a navegação dos clientes, reposicionando as setas e os nomes:

![imagicas-responsivo-01](https://cloud.githubusercontent.com/assets/3632627/5184681/95ea94c2-74a0-11e4-9ed1-f66f288de931.png)

Na versão em tela grande, ai elas gostariam que a imagem estourasse sempre que tivesse altura e largura para tal, veja como fica:

![imagicas-bigscreen](https://cloud.githubusercontent.com/assets/3632627/5184736/ed17e290-74a0-11e4-8377-ee72f03f2a94.png)

Da para deixar a imagem estourada sempre, mas respeitando sua altura?

**Comment by matheusgimenez** [comment]
A da imagem em telas grandes acho que está ok.. assim como tamanho da imagem em mobile.

Agora quanto ao nome do cliente em mobile.. pode me ajudar com isso? Onde eu poderia posicionar o nome?

**Comment by diegorojas** [comment]
Legal, não da para mudar a posição das setas? porque com mais espaço entre as setas, era só reposicionar para centralizar.. 

Poderia ser até as duas setas juntas à esquerda e depois o nome. 

Se não der para mexer na posição da seta, prefiro que o nome fique em cima da imagem em uma caixa preta, na esquerda embaixo. Ajudei?

**Comment by diegorojas** [comment]
Ei @matheusgimenez , olha o que eu te falei, eu vejo essa tarja preta embaixo da imagem aqui:

![imagicas-pau-na visu-imagem](https://cloud.githubusercontent.com/assets/3632627/5191015/15054ee2-74d2-11e4-91f4-5427f0fa9cfc.png)

Ai se eu chego e tiro a margin-bottom negativa, fica beleza:
![imagicas-pau-na visu-imagem-sem-margem](https://cloud.githubusercontent.com/assets/3632627/5191021/229d820e-74d2-11e4-9b8d-58e2cb7b16a4.png)

Veja ai.

**Comment by diegorojas** [comment]
Ei cara, a parte da imagem principal está resolvida! Obrigado.

Mas aqui ainda na versão responsiva ta caos. Veja:

![bug-clientes](https://cloud.githubusercontent.com/assets/3632627/5192472/e7b47cd0-74de-11e4-8293-5c9efd8f8b2b.png)

Rola uma rolagem bem grande tanto para cima como para baixo, e depois o rodapé ainda aparece por de trás do carrousel.

**Comment by matheusgimenez** [comment]
A ideia era não ter esse rodapé na pagina clientes

**Comment by diegorojas** [comment]
Exatamente! :) Não é para ter mesmo :)

**Comment by diegorojas** [comment]
Por mim estava tudo certo. Mas vou aguardar essa conversa que o Lucas iniciou com vc ok?
