### ISSUE TITLE
Mudança Pag Laboratório.

### ISSUE THREAD

**Issue by diegorojas** [brainwp/imagicas-theme#8]
@matheusgimenez tem uma coisa que eu não consegui fazer e to de saida já para reunião :(

Elas queriam que na pag laboratorio os itens "Simples" 
![itens-simples](https://cloud.githubusercontent.com/assets/3632627/5227582/c8c7ea34-76e4-11e4-8859-6347a903d544.png)

Ficassem abaixo do texto de introdução da página

E ai o loop com 2 videos em uma coluna, virasse um loop de 4 ou 6 videos em duas colunas

![itens-videos](https://cloud.githubusercontent.com/assets/3632627/5227595/f32c2470-76e4-11e4-805d-9cc9c1b81696.png)

O que ficar mais harmônico, acho que por hora elas tem 4 videos prontos e estão terminando o 5º.

**Comment by matheusgimenez** [comment]
Veja se está ok!

Acabei de subir pro beta também :)

**Comment by diegorojas** [comment]
Legal e também aprovado a forma como resolveu o responsivo em duas colunas de vídeo
