### ISSUE TITLE
Teaser Imagicas abre outra Janela

### ISSUE THREAD

**Issue by LuwkasLima** [brainwp/imagicas-theme#9]
Oi Pessoar,

Quando clico no Teaser do Imagicas (video de 22 anos) ele alem de abrir o "Pop up", tambem abre a pagina do post como imagem abaixo. Esta funcionando diferente dos outros videos.
![screenshot from 2014-12-14 11 32 23](https://cloud.githubusercontent.com/assets/5949986/5428335/1e077d14-8385-11e4-9046-d6863dee2d8a.png)

**Comment by matheusgimenez** [comment]
Deixa comigo que amanhã de manhã logo após eu terminar as tarefas do techcd eu resolvo todos os bugs relatados no email ok?

**Comment by LuwkasLima** [comment]
Suave man, só te coloquei pq tinha esquecido na real...

Mas foca la no TechCD e depois faz essa. Se não der pra fazer amanha não se preocupa, damos um jeito!
